#!/bin/bash
# Universal Network Bond Manager - lang_en.sh

declare -gA TEXT

# ENGLISCHE TEXTE
TEXT["en","TITLE"]="💻 Universal Network Bond Manager"
TEXT["en","CONFIG_TITLE"]="⚙️ Current Configuration"
TEXT["en","MENU_TITLE"]="Main Menu"
TEXT["en","ACTIVATE"]="⚡ Activate Bonding (With Backup)"
TEXT["en","DEACTIVATE"]="🚫 Deactivate/Delete Bonding (With Restore)"
TEXT["en","SPEEDTEST"]="🚀 Speedtest (Auto-Server)"
TEXT["en","DIAGNOSE"]="🩺 Diagnosis/Status Check"
TEXT["en","EMERGENCY"]="🚨 Emergency Repair (Revert to DHCP)"
TEXT["en","PACKAGE_MGMT"]="📦 Package Management (Install/Remove Tools)"
TEXT["en","CONFIG_MENU"]="🛠️ Change Configuration"
TEXT["en","EXIT"]="🚪 Exit"
TEXT["en","SELECT_ADAPTERS"]="Select Adapters for Bonding"
TEXT["en","ENTER_IP"]="Enter Static IP Address (e.g., 192.168.31.250/24)"
TEXT["en","ENTER_GATEWAY"]="Enter Default Gateway (e.g., 192.168.31.1)"
TEXT["en","ENTER_DNS"]="Enter DNS Server (e.g., 8.8.8.8)"
TEXT["en","SELECT_PRIMARY"]="Select Primary Slave (for Active-Backup)"
TEXT["en","SUCCESS_ACTIVATE"]="✅ BONDING ACTIVATED SUCCESSFULLY"
TEXT["en","SUCCESS_DEACTIVATE"]="✅ BONDING DEACTIVATED. Primary Slave is now running with DHCP."
TEXT["en","PRESS_ENTER"]="Press Enter to continue..."
TEXT["en","INVALID_CHOICE"]="Invalid choice."
TEXT["en","SLAVE_RUNNING"]="Active Slave"
TEXT["en","MII_STATUS_UP"]="✅ MII STATUS: Link is active."
TEXT["en","MII_STATUS_DOWN"]="⚠️ MII STATUS: Link is DOWN."
TEXT["en","ROUTE_CORRECT"]="✅ ROUTE CORRECT: $BOND_IFACE is the default interface."
TEXT["en","ROUTE_ERROR"]="❌ ROUTE ERROR: $BOND_IFACE did NOT take over the route."
TEXT["en","TOOL_NOT_FOUND"]="ERROR: Tool '$SPEEDTEST_TOOL' not found."
TEXT["en","BACKUP_CREATED"]="✅ Backup of active NM profiles created in: $BACKUP_DIR"
TEXT["en","BACKUP_FAILED"]="❌ Backup failed or no NM profiles found."
TEXT["en","RESTORE_SUCCESS"]="✅ NM profiles successfully restored from backup."
TEXT["en","RESTORE_FAILED"]="❌ Restore failed or no backup found."
TEXT["en","EMERGENCY_CONFIRM"]="WARNING! This will delete ALL Bond profiles. Continue (y/n)? "
TEXT["en","EMERGENCY_SUCCESS"]="✅ EMERGENCY REPAIR: System should be back online via $PRIMARY_SLAVE."
TEXT["en","SLAVE_ADAPTERS"]="Adapters (Slaves)"
TEXT["en","PRIMARY_SLAVE_ADAPTER"]="Primary Slave"
TEXT["en","IP_ADDRESS"]="Static IP"
TEXT["en","IP_SETTINGS"]="Change IP/Gateway/DNS"
TEXT["en","STARTING_SPEEDTEST_AUTO"]="Starting Speedtest (Automatic Server Selection)"
TEXT["en","STARTING_SPEEDTEST_MANUAL"]="Starting Speedtest (Manual Server ID: $SPEEDTEST_SERVER_IDS)"
TEXT["en","SPEEDTEST_CONFIG"]="Set Speedtest Server ID"
TEXT["en","ENTER_SERVER_ID"]="Enter optional Speedtest Server ID (Leave blank for Auto-Select):"
TEXT["en","CURRENT_SERVER_ID"]="Manual Server ID"
TEXT["en","PKGMGR_INFO"]="Package Manager Used"
TEXT["en","PKG_INSTALL_TITLE"]="Install Tools"
TEXT["en","PKG_REMOVE_TITLE"]="Uninstall Tools"
TEXT["en","PKG_INSTALL_DONE"]="Installation complete."
TEXT["en","PKG_REMOVE_DONE"]="Uninstallation complete."
TEXT["en","SELECT_LANGUAGE"]="Change Language (Current: "
TEXT["en","CONFIG_CHOICE_PROMPT"]="Choice"
TEXT["en","BACKUP_TITLE"]="Backup active NM Profiles"
TEXT["en","RESTORE_TITLE"]="Restoring NM Profiles"
