#!/bin/bash
# Universal Network Bond Manager - lang_de.sh

declare -gA TEXT

# DEUTSCHE TEXTE
TEXT["de","TITLE"]="💻 Universal Network Bond Manager"
TEXT["de","CONFIG_TITLE"]="⚙️ Aktuelle Konfiguration"
TEXT["de","MENU_TITLE"]="Hauptmenü"
TEXT["de","ACTIVATE"]="⚡ Bonding aktivieren (Mit Backup)"
TEXT["de","DEACTIVATE"]="🚫 Bonding deaktivieren / löschen (Mit Restore)"
TEXT["de","SPEEDTEST"]="🚀 Speedtest (Auto-Server)"
TEXT["de","DIAGNOSE"]="🩺 Diagnose/Status prüfen"
TEXT["de","EMERGENCY"]="🚨 Notfall-Reparatur (Zurück zu DHCP)"
TEXT["de","PACKAGE_MGMT"]="📦 Paketverwaltung (Tools installieren/entfernen)"
TEXT["de","CONFIG_MENU"]="🛠️ Konfiguration ändern"
TEXT["de","EXIT"]="🚪 Beenden"
TEXT["de","SELECT_ADAPTERS"]="Adapter für Bonding auswählen"
TEXT["de","ENTER_IP"]="Statische IP-Adresse eingeben (z.B. 192.168.31.250/24)"
TEXT["de","ENTER_GATEWAY"]="Standard-Gateway eingeben (z.B. 192.168.31.1)"
TEXT["de","ENTER_DNS"]="DNS-Server eingeben (z.B. 8.8.8.8)"
TEXT["de","SELECT_PRIMARY"]="Primären Slave auswählen (für Active-Backup)"
TEXT["de","SUCCESS_ACTIVATE"]="✅ BONDING ERFOLGREICH AKTIVIERT"
TEXT["de","SUCCESS_DEACTIVATE"]="✅ BONDING DEAKTIVIERT. Primary Slave läuft nun mit DHCP."
TEXT["de","PRESS_ENTER"]="Drücken Sie Enter, um fortzufahren..."
TEXT["de","INVALID_CHOICE"]="Ungültige Auswahl."
TEXT["de","SLAVE_RUNNING"]="Aktiver Slave"
TEXT["de","MII_STATUS_UP"]="✅ MII STATUS: Der Link ist aktiv."
TEXT["de","MII_STATUS_DOWN"]="⚠️ MII STATUS: Der Link ist DOWN."
TEXT["de","ROUTE_CORRECT"]="✅ ROUTE KORREKT: $BOND_IFACE ist die Standard-Schnittstelle."
TEXT["de","ROUTE_ERROR"]="❌ ROUTE FEHLER: $BOND_IFACE hat die Route NICHT übernommen."
TEXT["de","TOOL_NOT_FOUND"]="FEHLER: Das Tool '$SPEEDTEST_TOOL' wurde nicht gefunden."
TEXT["de","BACKUP_CREATED"]="✅ Backup der aktiven NM-Profile erstellt in: $BACKUP_DIR"
TEXT["de","BACKUP_FAILED"]="❌ Backup fehlgeschlagen oder keine NM-Profile gefunden."
TEXT["de","RESTORE_SUCCESS"]="✅ NM-Profile erfolgreich aus Backup wiederhergestellt."
TEXT["de","RESTORE_FAILED"]="❌ Wiederherstellung fehlgeschlagen oder kein Backup gefunden."
TEXT["de","EMERGENCY_CONFIRM"]="WARNUNG! Dies löscht ALLE Bond-Profile. Fortfahren (j/n)? "
TEXT["de","EMERGENCY_SUCCESS"]="✅ NOTFALL-REPARATUR: System sollte über $PRIMARY_SLAVE wieder online sein."
TEXT["de","SLAVE_ADAPTERS"]="Adapter (Slaves)"
TEXT["de","PRIMARY_SLAVE_ADAPTER"]="Primärer Slave"
TEXT["de","IP_ADDRESS"]="Statische IP"
TEXT["de","IP_SETTINGS"]="IP/Gateway/DNS ändern"
TEXT["de","STARTING_SPEEDTEST_AUTO"]="Starte Speedtest (automatische Server-Auswahl)"
TEXT["de","STARTING_SPEEDTEST_MANUAL"]="Starte Speedtest (Manuelle Server-ID: $SPEEDTEST_SERVER_IDS)"
TEXT["de","SPEEDTEST_CONFIG"]="Speedtest Server ID festlegen"
TEXT["de","ENTER_SERVER_ID"]="Optionale Speedtest Server ID eingeben (Leer lassen für Auto-Auswahl):"
TEXT["de","CURRENT_SERVER_ID"]="Manuelle Server ID"
TEXT["de","PKGMGR_INFO"]="Verwendeter Paketmanager"
TEXT["de","PKG_INSTALL_TITLE"]="Tools installieren"
TEXT["de","PKG_REMOVE_TITLE"]="Tools deinstallieren"
TEXT["de","PKG_INSTALL_DONE"]="Installation abgeschlossen."
TEXT["de","PKG_REMOVE_DONE"]="Deinstallation abgeschlossen."
TEXT["de","SELECT_LANGUAGE"]="Sprache ändern (Aktuell: "
TEXT["de","CONFIG_CHOICE_PROMPT"]="Wahl"
TEXT["de","BACKUP_TITLE"]="Backup aktiver NM-Profile"
TEXT["de","RESTORE_TITLE"]="Wiederherstellen von NM-Profilen"
